### ISSUE TITLE
yo

### ISSUE THREAD

**Issue by xZeroMCPE** [IrishPacks/Paradox#1]
Can you stop spamming BukkitPE? About "crediting" source. We've already done that, and it seems very immature of you to "think". it's okay to spam something. Come on? grow up!

**Comment by IrishPacks** [comment]
I sent two issues, that is not spamming. You never have credited them anywhere and if you have you did it after. Now please be quiet, stop telling me to grow up when you ban me after I tell you to credit them.

**Comment by ImagicalGamer** [comment]
@IrishPacks 1 issue = an issue 2 issues = spamming

**Comment by IrishPacks** [comment]
1st issue: credit sources
2nd issue: Asked why he banned me and made me look like a jackass after I was just telling him to credit sources.

**Comment by IrishPacks** [comment]
Also, I've asked you to DM me on Twitter so we can talk it out, but you didn't respond at all. I'm trying to be mature, but stealing code and then being so immature to make me look like a complete buffoon on your repository is not the way to go.

**Comment by JackNoordhuis** [comment]
More like xSkidMCPE lmao
